language: ruby
rvm: 2.3.1
cache: bundler
sudo: false
env:
  - API_KEY="TEST_API_KEY"
before_install:
  - "echo '--colour' > ~/.rspec"
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis-ci@example.com'
install: bundle install
notifications:
  email: false
