version: 2
jobs:
  build:
    working_directory: ~/lastfm
    docker:
      - image: cimg/ruby:3.0.5
    steps:
      - checkout

      - run:
          name: Bundle install
          command: bundle install

      - run:
          name: Run RSpec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress

      - store_test_results:
          path: test_results
